"""Unit tests for the reproducible-build lock/extras coverage gate (Lot 9,
scripts/check_lock_sync.py)."""

from __future__ import annotations

import json
import subprocess
import tomllib
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest
from scripts.check_lock_sync import (
    LockSyncError,
    check_build_backend_pin,
    check_dockerignore_and_copy,
    extract_dockerfile_extras,
    extract_lock_names,
    find_uncovered_dependencies,
    find_uncovered_transitive_dependencies,
    main,
    run_static_checks,
)

DOCKERFILE_OK = """\
FROM python:3.12-slim AS builder
RUN pip install pip==26.2 build==1.5.0 hatchling==1.32.0

FROM python:3.12-slim AS runtime
COPY requirements-lock.txt /tmp/requirements-lock.txt
RUN WHEEL_FILE=$(ls /tmp/*.whl) && \\
    pip install --no-cache-dir -c /tmp/requirements-lock.txt "${WHEEL_FILE}[v1,postgres]"
"""

LOCK_OK = """\
# This file was autogenerated by uv via the following command:
#    uv pip compile pyproject.toml --extra v1 --extra postgres -o requirements-lock.txt
fastapi==0.141.1
    # via modular-rag (pyproject.toml)
pydantic==2.13.4
    # via modular-rag (pyproject.toml)
httpx==0.28.1
    # via modular-rag (pyproject.toml)
pyyaml==6.0.3
    # via modular-rag (pyproject.toml)
structlog==26.1.0
    # via modular-rag (pyproject.toml)
psycopg==3.3.4
    # via modular-rag (pyproject.toml)
"""

LOCK_WITH_HASHES = """\
fastapi==0.141.1 \\
    --hash=sha256:1111111111111111111111111111111111111111111111111111111111111111 \\
    --hash=sha256:2222222222222222222222222222222222222222222222222222222222222222
    # via modular-rag (pyproject.toml)
pydantic==2.13.4 \\
    --hash=sha256:3333333333333333333333333333333333333333333333333333333333333333
    # via modular-rag (pyproject.toml)
"""

PYPROJECT_OK = """
[build-system]
requires = ["hatchling==1.32.0"]
build-backend = "hatchling.build"

[project]
dependencies = ["pydantic>=2.7", "pyyaml>=6.0", "httpx>=0.27", "structlog>=24.1"]

[project.optional-dependencies]
v1 = ["fastapi>=0.111"]
postgres = ["psycopg[binary,pool]>=3.1"]
"""

DOCKERIGNORE_OK = ".git/\n.venv/\ndocs/\n*.md\n"


def _pyproject(text: str = PYPROJECT_OK) -> dict:
    return tomllib.loads(text)


class TestExtractDockerfileExtras:
    def test_extracts_the_extras_list(self) -> None:
        assert extract_dockerfile_extras(DOCKERFILE_OK) == ["v1", "postgres"]

    def test_raises_when_no_install_line_present(self) -> None:
        with pytest.raises(LockSyncError, match="no 'pip install"):
            extract_dockerfile_extras("FROM python:3.12-slim\nRUN echo hi\n")

    def test_raises_on_conflicting_install_lines(self) -> None:
        text = DOCKERFILE_OK + '\nRUN pip install "${WHEEL_FILE}[v1,auth]"\n'
        with pytest.raises(LockSyncError, match="multiple, differing"):
            extract_dockerfile_extras(text)

    def test_ignores_commented_out_install_lines(self) -> None:
        text = 'FROM x\n# pip install "${WHEEL_FILE}[v1,dead]"\n' + DOCKERFILE_OK
        assert extract_dockerfile_extras(text) == ["v1", "postgres"]

    def test_handles_spaces_around_extras(self) -> None:
        text = 'FROM x AS runtime\nRUN pip install "${WHEEL_FILE}[ v1 , postgres ]"\n'
        assert extract_dockerfile_extras(text) == ["v1", "postgres"]


class TestExtractLockNames:
    def test_extracts_normalized_names_bare_format(self) -> None:
        names = extract_lock_names(LOCK_OK)
        assert "fastapi" in names
        assert "psycopg" in names
        assert len(names) == 6

    def test_extracts_names_from_hashed_multiline_format(self) -> None:
        names = extract_lock_names(LOCK_WITH_HASHES)
        assert names == {"fastapi", "pydantic"}

    def test_normalizes_underscores_and_dots_like_hyphens(self) -> None:
        names = extract_lock_names("Some_Package.Name==1.0\n")
        assert names == {"some-package-name"}

    def test_rejects_a_line_with_extras_brackets(self) -> None:
        with pytest.raises(LockSyncError, match="not a recognized lock entry"):
            extract_lock_names("uvicorn[standard]==0.52.1\n")

    def test_rejects_an_editable_line(self) -> None:
        with pytest.raises(LockSyncError, match="not a recognized lock entry"):
            extract_lock_names("-e .\n")

    def test_rejects_an_unpinned_specifier(self) -> None:
        with pytest.raises(LockSyncError, match="not a recognized lock entry"):
            extract_lock_names("fastapi>=0.111\n")

    def test_ignores_comments_and_blank_lines(self) -> None:
        names = extract_lock_names("# a comment\n\nfastapi==0.141.1\n    # via x\n")
        assert names == {"fastapi"}


class TestFindUncoveredDependencies:
    def test_no_problems_when_fully_covered(self) -> None:
        pyproject = _pyproject()
        lock_names = extract_lock_names(LOCK_OK)
        assert find_uncovered_dependencies(pyproject, ["v1", "postgres"], lock_names) == []

    def test_reports_missing_base_dependency(self) -> None:
        pyproject = _pyproject()
        lock_names = {"fastapi", "psycopg"}  # base deps missing
        problems = find_uncovered_dependencies(pyproject, ["v1", "postgres"], lock_names)
        assert any("base dependencies" in p for p in problems)

    def test_reports_missing_extra_dependency(self) -> None:
        pyproject = _pyproject()
        lock_names = {"pydantic", "pyyaml", "httpx", "structlog", "psycopg"}  # fastapi missing
        problems = find_uncovered_dependencies(pyproject, ["v1", "postgres"], lock_names)
        assert any("v1" in p and "fastapi" in p for p in problems)

    def test_reports_a_dockerfile_extra_that_does_not_exist_in_pyproject(self) -> None:
        pyproject = _pyproject()
        lock_names = extract_lock_names(LOCK_OK)
        problems = find_uncovered_dependencies(pyproject, ["v1", "typo-extra"], lock_names)
        assert any("does not exist" in p and "typo-extra" in p for p in problems)

    def test_a_lock_superset_covering_extra_extras_is_not_a_problem(self) -> None:
        """The lock is allowed to cover more than the Dockerfile installs
        (e.g. 'dev', kept for reproducible local/CI tooling) -- this is a
        subset check, not set equality."""
        pyproject = _pyproject()
        lock_names = extract_lock_names(LOCK_OK) | {"pytest", "mypy", "ruff"}
        assert find_uncovered_dependencies(pyproject, ["v1", "postgres"], lock_names) == []

    def test_direct_only_coverage_is_insufficient_by_itself(self) -> None:
        """Documents the exact gap HIGH-003 found: a lock naming only the
        two direct dependencies passes this direct-only check even though
        uvicorn[standard]'s real transitives (click, h11, httptools,
        uvloop, watchfiles, websockets) are entirely absent -- this is why
        find_uncovered_transitive_dependencies exists as a second, separate
        check, not a replacement for this one."""
        pyproject_text = """
[project]
dependencies = []
[project.optional-dependencies]
v1 = ["uvicorn[standard]>=0.29"]
"""
        pyproject = tomllib.loads(pyproject_text)
        lock_names = {"uvicorn"}  # every real transitive omitted
        assert find_uncovered_dependencies(pyproject, ["v1"], lock_names) == []


class TestFindUncoveredTransitiveDependencies:
    def test_skips_on_non_linux_host(self) -> None:
        with patch("scripts.check_lock_sync.platform.system", return_value="Windows"):
            problems, skip_reason = find_uncovered_transitive_dependencies(
                LOCK_OK, ["v1"], extract_lock_names(LOCK_OK)
            )
        assert problems == []
        assert skip_reason is not None
        assert "not Linux" in skip_reason

    def test_reports_packages_pip_would_install_but_lock_omits(self) -> None:
        fake_report = {
            "install": [
                {"metadata": {"name": "modular-rag"}},
                {"metadata": {"name": "fastapi"}},
                {"metadata": {"name": "uvloop"}},  # not in lock_names below
            ]
        }

        def fake_run(cmd, **kwargs):
            report_path = Path(cmd[cmd.index("--report") + 1])
            report_path.write_text(json.dumps(fake_report), encoding="utf-8")
            return MagicMock(returncode=0)

        with patch("scripts.check_lock_sync.platform.system", return_value="Linux"), patch(
            "scripts.check_lock_sync.subprocess.run", side_effect=fake_run
        ):
            problems, skip_reason = find_uncovered_transitive_dependencies(
                LOCK_OK, ["v1"], {"fastapi"}
            )
        assert skip_reason is None
        assert len(problems) == 1
        assert "uvloop" in problems[0]

    def test_excludes_the_project_itself_from_the_comparison(self) -> None:
        fake_report = {"install": [{"metadata": {"name": "modular-rag"}}]}

        def fake_run(cmd, **kwargs):
            report_path = Path(cmd[cmd.index("--report") + 1])
            report_path.write_text(json.dumps(fake_report), encoding="utf-8")
            return MagicMock(returncode=0)

        with patch("scripts.check_lock_sync.platform.system", return_value="Linux"), patch(
            "scripts.check_lock_sync.subprocess.run", side_effect=fake_run
        ):
            problems, skip_reason = find_uncovered_transitive_dependencies(LOCK_OK, ["v1"], set())
        assert skip_reason is None
        assert problems == []

    def test_no_problems_when_resolution_matches_the_lock(self) -> None:
        fake_report = {"install": [{"metadata": {"name": "fastapi"}}]}

        def fake_run(cmd, **kwargs):
            report_path = Path(cmd[cmd.index("--report") + 1])
            report_path.write_text(json.dumps(fake_report), encoding="utf-8")
            return MagicMock(returncode=0)

        with patch("scripts.check_lock_sync.platform.system", return_value="Linux"), patch(
            "scripts.check_lock_sync.subprocess.run", side_effect=fake_run
        ):
            problems, skip_reason = find_uncovered_transitive_dependencies(
                LOCK_OK, ["v1"], {"fastapi"}
            )
        assert skip_reason is None
        assert problems == []

    def test_a_linux_resolver_failure_is_a_hard_failure_not_a_skip(self) -> None:
        """Codex review HIGH-003, round 2: the previous version returned
        `([], skip_reason)` here too, so main() printed "OK" and exited 0
        even though the check never actually ran on the one platform it is
        supposed to be authoritative on. Reproduced directly (forced
        platform.system() to "Linux", subprocess.run to fail) before fixing
        it -- must now be a `problems` entry, never a silent skip."""
        with patch("scripts.check_lock_sync.platform.system", return_value="Linux"), patch(
            "scripts.check_lock_sync.subprocess.run",
            return_value=MagicMock(returncode=1, stderr="ResolutionImpossible"),
        ):
            problems, skip_reason = find_uncovered_transitive_dependencies(
                LOCK_OK, ["v1"], {"fastapi"}
            )
        assert skip_reason is None
        assert len(problems) == 1
        assert "did not produce a report" in problems[0]

    def test_a_linux_timeout_is_a_hard_failure_not_a_skip(self) -> None:
        with patch("scripts.check_lock_sync.platform.system", return_value="Linux"), patch(
            "scripts.check_lock_sync.subprocess.run",
            side_effect=subprocess.TimeoutExpired(cmd="pip", timeout=180),
        ):
            problems, skip_reason = find_uncovered_transitive_dependencies(
                LOCK_OK, ["v1"], {"fastapi"}
            )
        assert skip_reason is None
        assert len(problems) == 1
        assert "could not run" in problems[0]


class TestCheckBuildBackendPin:
    def test_passes_when_pyproject_and_dockerfile_pins_match(self) -> None:
        assert check_build_backend_pin(PYPROJECT_OK, DOCKERFILE_OK) == []

    def test_reports_unpinned_pyproject_backend(self) -> None:
        text = PYPROJECT_OK.replace('requires = ["hatchling==1.32.0"]', 'requires = ["hatchling"]')
        problems = check_build_backend_pin(text, DOCKERFILE_OK)
        assert any("does not pin an exact" in p for p in problems)

    def test_reports_missing_dockerfile_pin(self) -> None:
        dockerfile = DOCKERFILE_OK.replace(" hatchling==1.32.0", "")
        problems = check_build_backend_pin(PYPROJECT_OK, dockerfile)
        assert any("never installs a matching pinned" in p for p in problems)

    def test_reports_a_version_mismatch(self) -> None:
        dockerfile = DOCKERFILE_OK.replace("hatchling==1.32.0", "hatchling==1.30.0")
        problems = check_build_backend_pin(PYPROJECT_OK, dockerfile)
        assert any("these must match" in p for p in problems)

    def test_ignores_a_builder_stage_pin_that_is_actually_in_the_runtime_stage(self) -> None:
        """A Hatchling pin appearing only in the runtime stage (not builder,
        where the actual build runs) must not count as coverage."""
        dockerfile = (
            "FROM python:3.12-slim AS builder\nRUN pip install pip==26.2 build==1.5.0\n\n"
            "FROM python:3.12-slim AS runtime\nRUN pip install hatchling==1.32.0\n"
        )
        problems = check_build_backend_pin(PYPROJECT_OK, dockerfile)
        assert any("never installs a matching pinned" in p for p in problems)


class TestDockerignoreAndCopy:
    def test_no_problems_when_lock_is_copied_and_not_ignored(self) -> None:
        assert check_dockerignore_and_copy(DOCKERFILE_OK, DOCKERIGNORE_OK) == []

    def test_reports_lock_excluded_by_dockerignore(self) -> None:
        problems = check_dockerignore_and_copy(DOCKERFILE_OK, "requirements-lock.txt\n")
        assert any("dockerignore excludes" in p for p in problems)

    def test_reports_missing_copy_instruction(self) -> None:
        dockerfile = DOCKERFILE_OK.replace(
            "COPY requirements-lock.txt /tmp/requirements-lock.txt\n", ""
        )
        problems = check_dockerignore_and_copy(dockerfile, DOCKERIGNORE_OK)
        assert any("does not COPY" in p for p in problems)


class TestMainFailsClosedOnLinuxResolverFailure:
    """Codex review HIGH-003, round 2's own recommended regression: main()
    itself must exit non-zero when the transitive check cannot complete on
    Linux, not just the lower-level function in isolation -- covers the
    full path including how main() aggregates and prints the result."""

    def test_main_exits_nonzero_when_the_linux_resolver_fails(self) -> None:
        with patch("scripts.check_lock_sync.platform.system", return_value="Linux"), patch(
            "scripts.check_lock_sync.subprocess.run",
            return_value=MagicMock(returncode=1, stderr="ResolutionImpossible"),
        ):
            exit_code = main()
        assert exit_code != 0

    def test_main_exits_nonzero_on_a_linux_timeout(self) -> None:
        with patch("scripts.check_lock_sync.platform.system", return_value="Linux"), patch(
            "scripts.check_lock_sync.subprocess.run",
            side_effect=subprocess.TimeoutExpired(cmd="pip", timeout=180),
        ):
            exit_code = main()
        assert exit_code != 0

    def test_main_still_exits_zero_on_non_linux_when_everything_else_passes(self) -> None:
        """The real repo files pass every static check; on a non-Linux host
        the transitive sub-check must skip (not fail), so main() still
        succeeds overall -- this is the legitimate skip case, distinct from
        the two Linux-failure cases above."""
        with patch("scripts.check_lock_sync.platform.system", return_value="Windows"):
            exit_code = main()
        assert exit_code == 0


class TestRunStaticChecksOnRealRepoFiles:
    def test_the_actual_dockerfile_and_lock_pass(self) -> None:
        """Catches checker-assumption drift (a regex that silently stops
        matching the real files' current format) that fixture-only tests
        cannot -- this is the same file the CI gate itself reads. Only the
        static (portable) checks -- transitive resolution is exercised
        separately and is platform-gated."""
        root = Path(__file__).resolve().parents[3]
        dockerfile_text = (root / "Dockerfile").read_text(encoding="utf-8")
        lock_text = (root / "requirements-lock.txt").read_text(encoding="utf-8")
        pyproject_text = (root / "pyproject.toml").read_text(encoding="utf-8")
        pyproject = tomllib.loads(pyproject_text)
        dockerignore_text = (root / ".dockerignore").read_text(encoding="utf-8")

        problems, extras = run_static_checks(
            dockerfile_text, lock_text, pyproject, pyproject_text, dockerignore_text
        )
        assert problems == []
        assert extras == ["v1", "langgraph", "postgres", "auth"]
